management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831

logging:
  file:
    max-size: 100MB
    path: .

  pattern:
    console: "%clr(%date{HH:mm:ss.SSS}) %level [%clr(%mdc)] %clr(%logger{0}) : %message%n"
    file:    "%clr(%date) %level %clr(%logger :) %message%n"

  level:
    root: INFO
    org.springframework.web: INFO

server:
  port: 8181

spring:
  application:
    name: service-b

  output:
    ansi:
      enabled: ALWAYS

  main:
    allow-bean-definition-overriding: true

  datasource:
    platform: postgres
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:service_b_db
    username: user
    password: password

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      show-sql: true

    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true


  h2:
    console:
      enabled: true

swagger:
  package: org.spring.boot.distributed.tracing.instances.service.b
  title: Service B
  description: This service allows to create and store message info
  version: 0.0.1
  contact:
    name: Alexander A. Kropotin
    url: https://github.com/ololx
    email: ololx@icloud.com