version: '3'

services:
  jaeger:
    container_name: jaeger
    user: root
    restart: always
    build:
      context: jaeger/
      dockerfile: Dockerfile
    ports:
    - "6831:6831"
    - "16686:16686"
    volumes:
      - ./local/jaeger:/jaeger

  zipkin:
    container_name: zipkin
    user: root
    restart: always
    build:
      context: zipkin/
      dockerfile: Dockerfile
    ports:
    - "9411:9411"
    volumes:
      - ./local/zipkin:/zipkin